#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import testlib


# Nondestructive tests all run in the same running VM. This allows them to run in Packit, Fedora, and
# RHEL dist-git gating. They must not permanently change any file or configuration on the system in a
# way that influences other tests.
@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testBasic(self):
        b = self.browser
        m = self.machine

        m.execute("systemctl start smb || systemctl start smbd")

        self.login_and_go("/samba")
        b.wait_text(".pf-v6-c-card__title", "Samba service")
        b.wait_in_text(".pf-v6-c-label", "Running")

        # Shares table lists the default shares from the test image's smb.conf
        b.wait_visible("table[aria-label='Samba Shares Table']")

        # Create a new share
        b.click("button:contains('Create new share')")
        b.wait_visible(".pf-v6-c-modal-box")
        b.wait_text(".pf-v6-c-modal-box__title", "Create New Share")

        b.set_input_text("#share-name", "mytestshare")
        b.set_input_text("#share-path", "/tmp/mytestshare")
        b.click(".pf-v6-c-modal-box button:contains('Save Share')")

        # Directory does not exist -> offered to create it
        b.wait_text(".pf-v6-c-modal-box__title", "Create Missing Directory")
        b.click(".pf-v6-c-modal-box button:contains('Create Directory')")

        b.wait_not_present(".pf-v6-c-modal-box")
        b.wait_in_text("table[aria-label='Samba Shares Table']", "mytestshare")
        self.assertTrue(m.execute("test -d /tmp/mytestshare && echo yes").strip() == "yes")

        # Duplicate name is rejected inline, without touching the existing share
        b.click("button:contains('Create new share')")
        b.set_input_text("#share-name", "mytestshare")
        b.wait_in_text(".pf-v6-c-form__group-control", "already exists")

        b.click(".pf-v6-c-modal-box button:contains('Cancel')")
        b.wait_not_present(".pf-v6-c-modal-box")

        # Delete the share back out; confirmation modal explains the folder is kept
        b.click("table[aria-label='Samba Shares Table'] tr:contains('mytestshare') .pf-v6-c-menu-toggle")
        b.click("table[aria-label='Samba Shares Table'] .pf-v6-c-menu li:contains('Delete') button")
        b.wait_in_text(".pf-v6-c-modal-box", "not")
        b.click(".pf-v6-c-modal-box button:contains('Delete share')")
        b.wait_not_present(".pf-v6-c-modal-box")
        b.wait_not_in_text("table[aria-label='Samba Shares Table']", "mytestshare")

        self.assertTrue(m.execute("test -d /tmp/mytestshare && echo yes").strip() == "yes")
        m.execute("rmdir /tmp/mytestshare")


if __name__ == '__main__':
    testlib.test_main()
